name: Deploy Freedom 55

on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update setup.py
      run: |
        # Get the current version from setup.py
        CURRENT_VERSION=$(grep "version=" setup.py | cut -d '"' -f2)

        # Increment the patch version (e.g., 1.0.1 -> 1.0.2)
        NEW_VERSION=$(awk -F. '{$NF = sprintf("%0*d", length($NF), ($NF+1)%20); print}' <<< "$CURRENT_VERSION" | tr ' ' '.')

        # Update the version in setup.py using sed
        sed -i "s/$CURRENT_VERSION/$NEW_VERSION/g" setup.py
        git config --local user.email "${{ secrets.USERNAME }}"
        git config --local user.name "${{ secrets.USERNAME }}"
        git add setup.py
        cat setup.py
        git commit -m "Update version to $NEW_VERSION"
        git push origin

  build-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        CURRENT_VERSION=$(grep "version=" setup.py | cut -d '"' -f2)
        wget -qO - https://releases.jfrog.io/artifactory/jfrog-gpg-public/jfrog_public_gpg.key | sudo apt-key add -
        echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | sudo tee -a /etc/apt/sources.list && sudo apt update
        sudo apt install -y jfrog-cli-v2-jf && jf intro
        jf c add artifactory --url ${{ secrets.ARTIFACTORY_URL }} --user ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD}} --interactive=false
        jf pip-config --server-id-resolve=artifactory --repo-resolve=pypi
        jf pip install -r requirements.txt --build-name fd55-build-${CURRENT_VERSION} --build-number ${CURRENT_VERSION} --no-cache-dir --force-reinstall
        pip3 install build
    - name: Build package
      run: python3 -m build
    - name: Deploy package to Artifactory
      run: |
        CURRENT_VERSION=$(grep "version=" setup.py | cut -d '"' -f2)
        jf rt u --url ${{ secrets.JF_URL }} --password ${{ secrets.PASSWORD}} --user ${{ secrets.USERNAME }} dist/fd55-${CURRENT_VERSION}-py3-none-any.whl ${{ secrets.REPO }}/fd55/${CURRENT_VERSION}/fd55-${CURRENT_VERSION}-py3-none-any.whl --build-name fd55-build-${CURRENT_VERSION} --build-number ${CURRENT_VERSION}
        jf rt u --url ${{ secrets.JF_URL }} --password ${{ secrets.PASSWORD}} --user ${{ secrets.USERNAME }} dist/fd55-${CURRENT_VERSION}.tar.gz ${{ secrets.REPO }}/fd55/${CURRENT_VERSION}/fd55-${CURRENT_VERSION}.tar.gz --build-name fd55-build-${CURRENT_VERSION} --build-number ${CURRENT_VERSION}
    - name: Publish build info
      run: |
        CURRENT_VERSION=$(grep "version=" setup.py | cut -d '"' -f2)
        jf rt bag fd55-build-${CURRENT_VERSION} ${CURRENT_VERSION}
        jf rt bp fd55-build-${CURRENT_VERSION} ${CURRENT_VERSION}
    - name: Scan published build
      run: |
        jf bs fd55-build-${CURRENT_VERSION} ${CURRENT_VERSION}
    needs: [update-version]