name: Deploy Freedom 55

on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update setup.py
      run: |
        # Get the current version from setup.py
        CURRENT_VERSION=$(grep "version=" setup.py | cut -d '"' -f2)

        # Increment the patch version (e.g., 1.0.1 -> 1.0.2)
        NEW_VERSION=$(awk -F. '{$NF = sprintf("%0*d", length($NF), ($NF+1)%20); print}' <<< "$CURRENT_VERSION")

        # Update the version in setup.py using sed
        sed -i "s/$CURRENT_VERSION/$NEW_VERSION/g" setup.py
    - name: Commit version update
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GIT_REPO_TOKEN }}
        script: |
          git config --local user.email "${{ secrets.USERNAME }}"
          git config --local user.name "${{ secrets.USERNAME }}"
          git add setup.py
          git commit -m "Update version to $NEW_VERSION"
          git push origin HEAD:master

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade build
        pip3 install build
    - name: Build package
      run: python3 -m build
    needs: [update-version]

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jfrog/setup-jfrog-cli@v3
    - name: Deploy package to Artifactory
      run: |
        CURRENT_VERSION=$(grep "version=" setup.py | cut -d '"' -f2)
        echo ${CURRENT_VERSION}
        jf rt u --url ${{ secrets.JF_URL }} --password ${{ secrets.PASSWORD}} --user ${{ secrets.USERNAME }} dist/fd55-${CURRENT_VERSION}-py3-none-any.whl ${{ secrets.REPO }}/fd55/${CURRENT_VERSION}/fd55-${CURRENT_VERSION}-py3-none-any.whl
        jf rt u --url ${{ secrets.JF_URL }} --password ${{ secrets.PASSWORD}} --user ${{ secrets.USERNAME }} dist/fd55-${CURRENT_VERSION}.tar.gz ${{ secrets.REPO }}/fd55/${CURRENT_VERSION}/fd55-${CURRENT_VERSION}.tar.gz
    needs: [build]