name: Deploy Freedom 55

on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Update setup.py
      run: |
        # Get the current version from setup.py
        CURRENT_VERSION=$(grep "version=" setup.py | cut -d '"' -f2)

        # Increment the patch version (e.g., 1.0.1 -> 1.0.2)
        NEW_VERSION=$(awk -F. '{$NF = sprintf("%0*d", length($NF), ($NF+1)%20); print}' <<< "$CURRENT_VERSION")

        # Update the version in setup.py using sed
        sed -i "s/$CURRENT_VERSION/$NEW_VERSION/g" setup.py
    needs: [deploy]

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v2
      with:
        user: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        repository: ${{ secrets.REPO_URL}}